IM_TYPE_NLH = 0x1000
IM_TYPE_INTERP = IM_TYPE_NLH + 1
IM_TYPE_NZS = IM_TYPE_INTERP + 1

IM_TYPES = {IM_TYPE_NLH: 'Non-Linear Hyperbolic',
            IM_TYPE_INTERP: 'Interpolated',
            IM_TYPE_NZS: 'NZ Standard'}

INPUT_FORMAT_CSV = 0x2000
INPUT_FORMAT_LEGACY = INPUT_FORMAT_CSV + 1
INPUT_FORMATS = { INPUT_FORMAT_CSV: 'CSV',
                  INPUT_FORMAT_LEGACY: 'Old SLAT'}

INTERP_LINEAR = 0x3000
INTERP_LOGLOG = INTERP_LINEAR + 1
INTERP_TYPES = { INTERP_LINEAR: 'Linear',
                 INTERP_LOGLOG: 'Log-Log'}

EDP_FLAVOUR_USERDEF = 0x4000
EDP_FLAVOUR_POWERCURVE = EDP_FLAVOUR_USERDEF + 1
EDP_FLAVOURS = { EDP_FLAVOUR_USERDEF: 'User-defined',
                 EDP_FLAVOUR_POWERCURVE: 'Power Curve'}



