# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-13 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentsTab',
            fields=[
                ('key', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('ident', models.TextField()),
                ('name', models.TextField(blank=True, null=True)),
                ('system', models.TextField(blank=True, null=True)),
                ('structural', models.IntegerField()),
            ],
            options={
                'db_table': 'components_tab',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CostTab',
            fields=[
                ('rowid', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('state', models.IntegerField(blank=True, null=True)),
                ('min_cost', models.FloatField(blank=True, null=True)),
                ('max_cost', models.FloatField(blank=True, null=True)),
                ('dispersion', models.FloatField(blank=True, null=True)),
                ('lower_limit', models.IntegerField(blank=True, null=True)),
                ('upper_limit', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cost_tab',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DemandsTab',
            fields=[
                ('key', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'demands_tab',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EDP_Flavours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'slat_edp_flavours',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FragilityTab',
            fields=[
                ('rowid', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('state', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('repairs', models.TextField(blank=True, null=True)),
                ('median', models.FloatField(blank=True, null=True)),
                ('beta', models.FloatField(blank=True, null=True)),
                ('image', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fragility_tab',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IM_Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'slat_im_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Input_File_Formats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format_text', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'slat_input_file_formats',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Interpolation_Method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_text', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'slat_interpolation_method',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=128)),
                ('z', models.FloatField()),
                ('min_distance', models.FloatField(null=True)),
                ('max_disstance', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'slat_location',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PACT_CatsTab',
            fields=[
                ('rowid', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('ident', models.TextField(blank=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('formula', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pact_cats_tab',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnitsTab',
            fields=[
                ('key', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'units_tab',
                'managed': False,
            },
        ),
    ]
