# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-26 21:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EDP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField()),
                ('type', models.CharField(choices=[('D', 'Inter-story Drift'), ('A', 'Acceleration')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='EDP_Flavours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='EDP_Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('im', models.FloatField()),
                ('median_x', models.FloatField()),
                ('sd_ln_x', models.FloatField()),
                ('demand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slat.EDP')),
            ],
        ),
        migrations.CreateModel(
            name='EDP_PowerCurve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('median_x_a', models.FloatField()),
                ('median_x_b', models.FloatField()),
                ('sd_ln_x_a', models.FloatField()),
                ('sd_ln_x_b', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='IM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='IM_Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('im_value', models.FloatField()),
                ('rate', models.FloatField()),
                ('hazard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slat.IM')),
            ],
        ),
        migrations.CreateModel(
            name='IM_Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Input_File_Formats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format_text', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Interpolation_Method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_text', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=128)),
                ('z', models.FloatField()),
                ('min_distance', models.FloatField(null=True)),
                ('max_disstance', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NonLinearHyperbolic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_assy_float', models.FloatField()),
                ('im_asy_float', models.FloatField()),
                ('alpha_float', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='NZ_Standard_Curve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil_class', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='A', max_length=1)),
                ('period', models.FloatField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slat.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=50)),
                ('description_text', models.CharField(max_length=200)),
                ('floors', models.IntegerField(blank=True, null=True)),
                ('rarity', models.FloatField(default=0.0001)),
                ('IM', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slat.IM')),
            ],
        ),
        migrations.AddField(
            model_name='im',
            name='flavour',
            field=models.ForeignKey(default=4097, on_delete=django.db.models.deletion.CASCADE, to='slat.IM_Types'),
        ),
        migrations.AddField(
            model_name='im',
            name='interp_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slat.Interpolation_Method'),
        ),
        migrations.AddField(
            model_name='im',
            name='nlh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slat.NonLinearHyperbolic'),
        ),
        migrations.AddField(
            model_name='im',
            name='nzs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slat.NZ_Standard_Curve'),
        ),
        migrations.AddField(
            model_name='edp',
            name='flavour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='slat.EDP_Flavours'),
        ),
        migrations.AddField(
            model_name='edp',
            name='interpolation_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='slat.Interpolation_Method'),
        ),
        migrations.AddField(
            model_name='edp',
            name='powercurve',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='slat.EDP_PowerCurve'),
        ),
        migrations.AddField(
            model_name='edp',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slat.Project'),
        ),
    ]
