# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-26 21:52
from __future__ import unicode_literals

from django.db import migrations
from slat.constants import *

def load_stores(apps, schema_editor):
    EDP_Flavours = apps.get_model("slat", "EDP_Flavours")
    for id, name in EDP_FLAVOURS.items():
        EDP_Flavours(id=id, name_text=name).save()

    IM_Types = apps.get_model("slat", "IM_Types")
    for id, name in IM_TYPES.items():
        IM_Types(id=id, name_text=name).save()

    Input_File_Formats = apps.get_model("slat", "Input_File_Formats")
    for id, name in INPUT_FORMATS.items():
        Input_File_Formats(id=id, format_text=name).save()
        
    Interp_Methods = apps.get_model("slat", "Interpolation_Method")
    for id, name in INTERP_TYPES.items():
        Interp_Methods(id=id, method_text = name).save()
     
    IM_Types = apps.get_model("slat", "IM_Types")
    for id, name in IM_TYPES.items():
        if not (IM_Types.objects.filter(id=id)):
            IM_Types(id=id, name_text=name).save()

    locations = (
        (0, 'Kaitaia', 0.13, None, None),
        (1, 'Paihia/Russell', 0.13, None, None),
        (2, 'Kaikohe', 0.13, None, None),
        (3, 'Whangarei', 0.13, None, None),
        (4, 'Dargaville', 0.13, None, None),
        (5, 'Warkworth', 0.13, None, None),
        (6, 'Auckland', 0.13, None, None),
        (7, 'Manakau City', 0.13, None, None),
        (8, 'Waiuku', 0.13, None, None),
        (9, 'Pukekohe', 0.13, None, None),
        (10, 'Thames', 0.16, None, None),
        (11, 'Paeroa', 0.18, None, None),
        (12, 'Waihi', 0.18, None, None),
        (13, 'Huntly', 0.15, None, None),
        (14, 'Ngaruawahia', 0.15, None, None),
        (15, 'Morrinsville', 0.18, None, None),
        (16, 'Te Aroha', 0.18, None, None),
        (17, 'Tauranga', 0.20, None, None),
        (18, 'Mount Maunganui', 0.20, None, None),
        (19, 'Hamilton', 0.16, None, None),
        (20, 'Cambridge', 0.18, None, None),
        (21, 'Te Awamutu', 0.17, None, None),
        (22, 'Matamata', 0.19, None, None),
        (23, 'Te Puke', 0.22, None, None),
        (24, 'Putaruru', 0.21, None, None),
        (25, 'Tokoroa', 0.21, None, None),
        (26, 'Otorohanga', 0.17, None, None),
        (27, 'Te Kuiti', 0.18, None, None),
        (28, 'Mangakino', 0.21, None, None),
        (29, 'Rotorua', 0.24, None, None),
        (30, 'Kawerau', 0.29, None, None),
        (31, 'Whakatane', 0.30, None, None),
        (32, 'Opotiki', 0.30, None, None),
        (33, 'Ruatoria', 0.33, None, None),
        (34, 'Murupara', 0.30, None, None),
        (35, 'Taupo', 0.28, None, None),
        (36, 'Taumarunui', 0.21, None, None),
        (37, 'Turangi', 0.27, None, None),
        (38, 'Gisborne', 0.36, None, None),
        (39, 'Wairoa', 0.37, None, None),
        (40, 'Waitara', 0.18, None, None),
        (41, 'New Plymouth', 0.18, None, None),
        (42, 'Inglewood', 0.18, None, None),
        (43, 'Stratford', 0.18, None, None),
        (44, 'Opunake', 0.18, None, None),
        (45, 'Hawera', 0.18, None, None),
        (46, 'Patea', 0.19, None, None),
        (47, 'Ohakune', 0.27, None, None),
        (48, 'Waiouru', 0.29, None, None),
        (49, 'Napier', 0.38, None, None),
        (50, 'Hastings', 0.39, None, None),
        (51, 'Wanganui', 0.25, None, None),
        (52, 'Waipawa', 0.41, None, None),
        (53, 'Waipukurau', 0.41, None, None),
        (54, 'Taihape', 0.33, None, None),
        (55, 'Marton', 0.30, None, None),
        (56, 'Bulls', 0.31, None, None),
        (57, 'Feilding', 0.37, None, None),
        (58, 'Palmerston North', 0.38, 8, 16, None, None),
        (59, 'Dannevirke', 0.42, 10, 10, None, None),
        (60, 'Woodville', 0.41, 0, 2, None, None),
        (61, 'Pahiatua', 0.42, 8, 8, None, None),
        (62, 'Foxton/Foxton Beach', 0.36, None, None),
        (63, 'Levin', 0.40, None, None),
        (64, 'Otaki', 0.40, None, None),
        (65, 'Waikanae', 0.40, 15, 20, None, None),
        (66, 'Paraparaumu', 0.40, 14, 20, None, None),
        (67, 'Masterton', 0.42, 6, 10, None, None),
        (68, 'Porirua', 0.40, 8, 12, None, None),
        (69, 'Wellington CBD (north of Basin Reserve)', 0.40, 0, 2, None, None),
        (70, 'Wellington', 0.40, 0, 8, None, None),
        (71, 'Hutt Valley-south of Taita Gorge', 0.40, 0, 4, None, None),
        (72, 'Upper Hutt', 0.42, 0, 2, None, None),
        (73, 'Eastbourne-Point Howard', 0.40, 4, 8, None, None),
        (74, 'Wainuiomata', 0.40, 5, 8, None, None),
        (75, 'Takaka', 0.23, None, None),
        (76, 'Motueka', 0.26, None, None),
        (77, 'Nelson', 0.27, None, None),
        (78, 'Picton', 0.30, 16, 16, None, None),
        (79, 'Blenheim', 0.33, 0, 5, None, None),
        (80, 'St Arnaud', 0.36, 0, 2, None, None),
        (81, 'Westport', 0.30, None, None),
        (82, 'Reefton', 0.37, None, None),
        (83, 'Murchison', 0.34, None, None),
        (84, 'Springs Junction', 0.45, 3, 3, None, None),
        (85, 'Hanmer Springs', 0.55, 2, 6, None, None),
        (86, 'Seddon', 0.40, 6, 6, None, None),
        (87, 'Ward', 0.40, 4, 4, None, None),
        (88, 'Cheviot', 0.40, None, None),
        (89, 'Greymouth', 0.37, None, None),
        (90, 'Kaikoura', 0.42, 12, 12, None, None),
        (91, 'Harihari', 0.46, 4, 4, None, None),
        (92, 'Hokitika', 0.45, None, None),
        (93, 'Fox Glacier', 0.44, 0, 2, None, None),
        (94, 'Franz Josef', 0.44, 0, 2, None, None),
        (95, 'Otira', 0.60, 3, 3, None, None),
        (96, 'Arthurs Pass', 0.60, 12, 12, None, None),
        (97, 'Rangiora', 0.33, None, None),
        (98, 'Darfield', 0.30, None, None),
        (99, 'Akaroa', 0.16, None, None),
        (100, 'Christchurch', 0.22, None, None),
        (101, 'Geraldine', 0.19, None, None),
        (102, 'Ashburton', 0.20, None, None),
        (103, 'Fairlie', 0.24, None, None),
        (104, 'Temuka', 0.17, None, None),
        (105, 'Timaru', 0.15, None, None),
        (106, 'Mt Cook', 0.38, None, None),
        (107, 'Twizel', 0.27, None, None),
        (108, 'Waimate', 0.14, None, None),
        (109, 'Cromwell', 0.24, None, None),
        (110, 'Wanaka', 0.30, None, None),
        (111, 'Arrowtown', 0.30, None, None),
        (112, 'Alexandra', 0.21, None, None),
        (113, 'Queenstown', 0.32, None, None),
        (114, 'Milford Sound', 0.54, None, None),
        (115, 'Palmerston', 0.13, None, None),
        (116, 'Oamaru', 0.13, None, None),
        (117, 'Dunedin', 0.13, None, None),
        (118, 'Mosgiel', 0.13, None, None),
        (119, 'Riverton', 0.20, None, None),
        (120, 'Te Anau', 0.36, None, None),
        (121, 'Gore', 0.18, None, None),
        (122, 'Winton', 0.20, None, None),
        (123, 'Balclutha', 0.13, None, None),
        (124, 'Mataura', 0.17, None, None),
        (125, 'Bluff', 0.15, None, None),
        (126, 'Invercargill', 0.17, None, None),
        (127, 'Oban', 0.14, None, None))
 
    for l in locations:
        Location = apps.get_model("slat", "Location")
        Location(l[0], l[1], l[2], l[3], l[4]).save()


class Migration(migrations.Migration):

    dependencies = [
        ('slat', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_stores),
    ]
