# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-27 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slat', '0002_auto_20170626_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description_text',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
