# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-28 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slat', '0003_auto_20170627_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edp_powercurve',
            name='median_x_a',
            field=models.FloatField(default=0.1),
        ),
        migrations.AlterField(
            model_name='edp_powercurve',
            name='median_x_b',
            field=models.FloatField(default=1.5),
        ),
        migrations.AlterField(
            model_name='edp_powercurve',
            name='sd_ln_x_a',
            field=models.FloatField(default=0.5),
        ),
        migrations.AlterField(
            model_name='edp_powercurve',
            name='sd_ln_x_b',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='nonlinearhyperbolic',
            name='alpha_float',
            field=models.FloatField(default=62.2),
        ),
        migrations.AlterField(
            model_name='nonlinearhyperbolic',
            name='im_asy_float',
            field=models.FloatField(default=29.8),
        ),
        migrations.AlterField(
            model_name='nonlinearhyperbolic',
            name='v_assy_float',
            field=models.FloatField(default=1221),
        ),
        migrations.AlterField(
            model_name='nz_standard_curve',
            name='period',
            field=models.FloatField(default=1.5),
        ),
    ]
