# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 01:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slat', '0004_auto_20170628_0012'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentsTab',
            fields=[
                ('key', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('ident', models.TextField()),
                ('name', models.TextField(blank=True, null=True)),
                ('system', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'components_tab',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CostTab',
            fields=[
                ('rowid', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('state', models.IntegerField(blank=True, null=True)),
                ('min_cost', models.FloatField(blank=True, null=True)),
                ('max_cost', models.FloatField(blank=True, null=True)),
                ('dispersion', models.FloatField(blank=True, null=True)),
                ('lower_limit', models.IntegerField(blank=True, null=True)),
                ('upper_limit', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cost_tab',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DemandsTab',
            fields=[
                ('key', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'demands_tab',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FragilityTab',
            fields=[
                ('rowid', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('state', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('repairs', models.TextField(blank=True, null=True)),
                ('median', models.FloatField(blank=True, null=True)),
                ('beta', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fragility_tab',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnitsTab',
            fields=[
                ('key', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'units_tab',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Component_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slat.ComponentsTab')),
                ('demand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slat.EDP')),
            ],
        ),
    ]
