# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slat', '0005_component_group_componentstab_costtab_demandstab_djangomigrations_fragilitytab_unitstab'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='mean_cost_collapse',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='mean_cost_demolition',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='mean_im_collapse',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='mean_im_demolition',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='sd_ln_cost_collapse',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='sd_ln_cost_demolition',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='sd_ln_im_collapse',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='sd_ln_im_demolition',
            field=models.FloatField(null=True),
        ),
    ]
