# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slat', '0006_auto_20170911_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='mean_cost_collapse',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='mean_cost_demolition',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='mean_im_collapse',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='mean_im_demolition',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='sd_ln_cost_collapse',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='sd_ln_cost_demolition',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='sd_ln_im_collapse',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='sd_ln_im_demolition',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
