# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slat', '0008_auto_20170920_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='floors',
            field=models.IntegerField(),
        ),
    ]
