# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-27 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slat', '0009_auto_20170920_0340'),
    ]

    operations = [
        migrations.CreateModel(
            name='PACT_CatsTab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident', models.TextField(blank=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('formula', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
