# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-27 23:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slat', '0010_pact_catstab'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pact_catstab',
            options={'managed': False},
        ),
    ]
