# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-27 23:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slat', '0011_auto_20170927_2328'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pact_catstab',
            table='pact_cats_tab',
        ),
    ]
