# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-12 00:03
from __future__ import unicode_literals
from slat.models import *

from django.db import migrations

def create_levels(apps, schema_editor):
    for project in Project.objects.all():
        if not Level.objects.filter(project=project):
            for f in range(project.floors + 1):
                Level(project=project,
                      level=f,
                      label=project.floor_label(f)).save()
    
class Migration(migrations.Migration):

    dependencies = [
        ('slat', '0015_auto_20171211_2351'),
    ]

    operations = [
        migrations.RunPython(create_levels)
    ]
