# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-12 00:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slat', '0016_auto_20171212_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='floors',
        ),
    ]
