# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-12 02:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slat', '0017_remove_project_floors'),
    ]

    operations = [
        migrations.AddField(
            model_name='edp',
            name='level',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='slat.Level'),
            preserve_default=False,
        ),
    ]
