# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-12 02:47
from __future__ import unicode_literals

from django.db import migrations
from slat.models import *


def change_edp_floors_to_levels(apps, schema_editor):
    for edp in EDP.objects.all():
        edp.level = Level.objects.get(project=edp.project, level=edp.floor)
        edp.save()

class Migration(migrations.Migration):

    dependencies = [
        ('slat', '0018_edp_level'),
    ]

    operations = [
        migrations.RunPython(change_edp_floors_to_levels)
    ]
