PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE "slat_location" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "location" varchar(128) NOT NULL, "z" real NOT NULL, "min_distance" real NULL, "max_disstance" real NULL);
INSERT INTO "slat_location" VALUES(0,'Kaitaia',0.13,NULL,NULL);
INSERT INTO "slat_location" VALUES(1,'Paihia/Russell',0.13,NULL,NULL);
INSERT INTO "slat_location" VALUES(2,'Kaikohe',0.13,NULL,NULL);
INSERT INTO "slat_location" VALUES(3,'Whangarei',0.13,NULL,NULL);
INSERT INTO "slat_location" VALUES(4,'Dargaville',0.13,NULL,NULL);
INSERT INTO "slat_location" VALUES(5,'Warkworth',0.13,NULL,NULL);
INSERT INTO "slat_location" VALUES(6,'Auckland',0.13,NULL,NULL);
INSERT INTO "slat_location" VALUES(7,'Manakau City',0.13,NULL,NULL);
INSERT INTO "slat_location" VALUES(8,'Waiuku',0.13,NULL,NULL);
INSERT INTO "slat_location" VALUES(9,'Pukekohe',0.13,NULL,NULL);
INSERT INTO "slat_location" VALUES(10,'Thames',0.16,NULL,NULL);
INSERT INTO "slat_location" VALUES(11,'Paeroa',0.18,NULL,NULL);
INSERT INTO "slat_location" VALUES(12,'Waihi',0.18,NULL,NULL);
INSERT INTO "slat_location" VALUES(13,'Huntly',0.15,NULL,NULL);
INSERT INTO "slat_location" VALUES(14,'Ngaruawahia',0.15,NULL,NULL);
INSERT INTO "slat_location" VALUES(15,'Morrinsville',0.18,NULL,NULL);
INSERT INTO "slat_location" VALUES(16,'Te Aroha',0.18,NULL,NULL);
INSERT INTO "slat_location" VALUES(17,'Tauranga',0.2,NULL,NULL);
INSERT INTO "slat_location" VALUES(18,'Mount Maunganui',0.2,NULL,NULL);
INSERT INTO "slat_location" VALUES(19,'Hamilton',0.16,NULL,NULL);
INSERT INTO "slat_location" VALUES(20,'Cambridge',0.18,NULL,NULL);
INSERT INTO "slat_location" VALUES(21,'Te Awamutu',0.17,NULL,NULL);
INSERT INTO "slat_location" VALUES(22,'Matamata',0.19,NULL,NULL);
INSERT INTO "slat_location" VALUES(23,'Te Puke',0.22,NULL,NULL);
INSERT INTO "slat_location" VALUES(24,'Putaruru',0.21,NULL,NULL);
INSERT INTO "slat_location" VALUES(25,'Tokoroa',0.21,NULL,NULL);
INSERT INTO "slat_location" VALUES(26,'Otorohanga',0.17,NULL,NULL);
INSERT INTO "slat_location" VALUES(27,'Te Kuiti',0.18,NULL,NULL);
INSERT INTO "slat_location" VALUES(28,'Mangakino',0.21,NULL,NULL);
INSERT INTO "slat_location" VALUES(29,'Rotorua',0.24,NULL,NULL);
INSERT INTO "slat_location" VALUES(30,'Kawerau',0.29,NULL,NULL);
INSERT INTO "slat_location" VALUES(31,'Whakatane',0.3,NULL,NULL);
INSERT INTO "slat_location" VALUES(32,'Opotiki',0.3,NULL,NULL);
INSERT INTO "slat_location" VALUES(33,'Ruatoria',0.33,NULL,NULL);
INSERT INTO "slat_location" VALUES(34,'Murupara',0.3,NULL,NULL);
INSERT INTO "slat_location" VALUES(35,'Taupo',0.28,NULL,NULL);
INSERT INTO "slat_location" VALUES(36,'Taumarunui',0.21,NULL,NULL);
INSERT INTO "slat_location" VALUES(37,'Turangi',0.27,NULL,NULL);
INSERT INTO "slat_location" VALUES(38,'Gisborne',0.36,NULL,NULL);
INSERT INTO "slat_location" VALUES(39,'Wairoa',0.37,NULL,NULL);
INSERT INTO "slat_location" VALUES(40,'Waitara',0.18,NULL,NULL);
INSERT INTO "slat_location" VALUES(41,'New Plymouth',0.18,NULL,NULL);
INSERT INTO "slat_location" VALUES(42,'Inglewood',0.18,NULL,NULL);
INSERT INTO "slat_location" VALUES(43,'Stratford',0.18,NULL,NULL);
INSERT INTO "slat_location" VALUES(44,'Opunake',0.18,NULL,NULL);
INSERT INTO "slat_location" VALUES(45,'Hawera',0.18,NULL,NULL);
INSERT INTO "slat_location" VALUES(46,'Patea',0.19,NULL,NULL);
INSERT INTO "slat_location" VALUES(47,'Ohakune',0.27,NULL,NULL);
INSERT INTO "slat_location" VALUES(48,'Waiouru',0.29,NULL,NULL);
INSERT INTO "slat_location" VALUES(49,'Napier',0.38,NULL,NULL);
INSERT INTO "slat_location" VALUES(50,'Hastings',0.39,NULL,NULL);
INSERT INTO "slat_location" VALUES(51,'Wanganui',0.25,NULL,NULL);
INSERT INTO "slat_location" VALUES(52,'Waipawa',0.41,NULL,NULL);
INSERT INTO "slat_location" VALUES(53,'Waipukurau',0.41,NULL,NULL);
INSERT INTO "slat_location" VALUES(54,'Taihape',0.33,NULL,NULL);
INSERT INTO "slat_location" VALUES(55,'Marton',0.3,NULL,NULL);
INSERT INTO "slat_location" VALUES(56,'Bulls',0.31,NULL,NULL);
INSERT INTO "slat_location" VALUES(57,'Feilding',0.37,NULL,NULL);
INSERT INTO "slat_location" VALUES(58,'Palmerston North',0.38,8.0,16.0);
INSERT INTO "slat_location" VALUES(59,'Dannevirke',0.42,10.0,10.0);
INSERT INTO "slat_location" VALUES(60,'Woodville',0.41,0.0,2.0);
INSERT INTO "slat_location" VALUES(61,'Pahiatua',0.42,8.0,8.0);
INSERT INTO "slat_location" VALUES(62,'Foxton/Foxton Beach',0.36,NULL,NULL);
INSERT INTO "slat_location" VALUES(63,'Levin',0.4,NULL,NULL);
INSERT INTO "slat_location" VALUES(64,'Otaki',0.4,NULL,NULL);
INSERT INTO "slat_location" VALUES(65,'Waikanae',0.4,15.0,20.0);
INSERT INTO "slat_location" VALUES(66,'Paraparaumu',0.4,14.0,20.0);
INSERT INTO "slat_location" VALUES(67,'Masterton',0.42,6.0,10.0);
INSERT INTO "slat_location" VALUES(68,'Porirua',0.4,8.0,12.0);
INSERT INTO "slat_location" VALUES(69,'Wellington CBD (north of Basin Reserve)',0.4,0.0,2.0);
INSERT INTO "slat_location" VALUES(70,'Wellington',0.4,0.0,8.0);
INSERT INTO "slat_location" VALUES(71,'Hutt Valley-south of Taita Gorge',0.4,0.0,4.0);
INSERT INTO "slat_location" VALUES(72,'Upper Hutt',0.42,0.0,2.0);
INSERT INTO "slat_location" VALUES(73,'Eastbourne-Point Howard',0.4,4.0,8.0);
INSERT INTO "slat_location" VALUES(74,'Wainuiomata',0.4,5.0,8.0);
INSERT INTO "slat_location" VALUES(75,'Takaka',0.23,NULL,NULL);
INSERT INTO "slat_location" VALUES(76,'Motueka',0.26,NULL,NULL);
INSERT INTO "slat_location" VALUES(77,'Nelson',0.27,NULL,NULL);
INSERT INTO "slat_location" VALUES(78,'Picton',0.3,16.0,16.0);
INSERT INTO "slat_location" VALUES(79,'Blenheim',0.33,0.0,5.0);
INSERT INTO "slat_location" VALUES(80,'St Arnaud',0.36,0.0,2.0);
INSERT INTO "slat_location" VALUES(81,'Westport',0.3,NULL,NULL);
INSERT INTO "slat_location" VALUES(82,'Reefton',0.37,NULL,NULL);
INSERT INTO "slat_location" VALUES(83,'Murchison',0.34,NULL,NULL);
INSERT INTO "slat_location" VALUES(84,'Springs Junction',0.45,3.0,3.0);
INSERT INTO "slat_location" VALUES(85,'Hanmer Springs',0.55,2.0,6.0);
INSERT INTO "slat_location" VALUES(86,'Seddon',0.4,6.0,6.0);
INSERT INTO "slat_location" VALUES(87,'Ward',0.4,4.0,4.0);
INSERT INTO "slat_location" VALUES(88,'Cheviot',0.4,NULL,NULL);
INSERT INTO "slat_location" VALUES(89,'Greymouth',0.37,NULL,NULL);
INSERT INTO "slat_location" VALUES(90,'Kaikoura',0.42,12.0,12.0);
INSERT INTO "slat_location" VALUES(91,'Harihari',0.46,4.0,4.0);
INSERT INTO "slat_location" VALUES(92,'Hokitika',0.45,NULL,NULL);
INSERT INTO "slat_location" VALUES(93,'Fox Glacier',0.44,0.0,2.0);
INSERT INTO "slat_location" VALUES(94,'Franz Josef',0.44,0.0,2.0);
INSERT INTO "slat_location" VALUES(95,'Otira',0.6,3.0,3.0);
INSERT INTO "slat_location" VALUES(96,'Arthurs Pass',0.6,12.0,12.0);
INSERT INTO "slat_location" VALUES(97,'Rangiora',0.33,NULL,NULL);
INSERT INTO "slat_location" VALUES(98,'Darfield',0.3,NULL,NULL);
INSERT INTO "slat_location" VALUES(99,'Akaroa',0.16,NULL,NULL);
INSERT INTO "slat_location" VALUES(100,'Christchurch',0.22,NULL,NULL);
INSERT INTO "slat_location" VALUES(101,'Geraldine',0.19,NULL,NULL);
INSERT INTO "slat_location" VALUES(102,'Ashburton',0.2,NULL,NULL);
INSERT INTO "slat_location" VALUES(103,'Fairlie',0.24,NULL,NULL);
INSERT INTO "slat_location" VALUES(104,'Temuka',0.17,NULL,NULL);
INSERT INTO "slat_location" VALUES(105,'Timaru',0.15,NULL,NULL);
INSERT INTO "slat_location" VALUES(106,'Mt Cook',0.38,NULL,NULL);
INSERT INTO "slat_location" VALUES(107,'Twizel',0.27,NULL,NULL);
INSERT INTO "slat_location" VALUES(108,'Waimate',0.14,NULL,NULL);
INSERT INTO "slat_location" VALUES(109,'Cromwell',0.24,NULL,NULL);
INSERT INTO "slat_location" VALUES(110,'Wanaka',0.3,NULL,NULL);
INSERT INTO "slat_location" VALUES(111,'Arrowtown',0.3,NULL,NULL);
INSERT INTO "slat_location" VALUES(112,'Alexandra',0.21,NULL,NULL);
INSERT INTO "slat_location" VALUES(113,'Queenstown',0.32,NULL,NULL);
INSERT INTO "slat_location" VALUES(114,'Milford Sound',0.54,NULL,NULL);
INSERT INTO "slat_location" VALUES(115,'Palmerston',0.13,NULL,NULL);
INSERT INTO "slat_location" VALUES(116,'Oamaru',0.13,NULL,NULL);
INSERT INTO "slat_location" VALUES(117,'Dunedin',0.13,NULL,NULL);
INSERT INTO "slat_location" VALUES(118,'Mosgiel',0.13,NULL,NULL);
INSERT INTO "slat_location" VALUES(119,'Riverton',0.2,NULL,NULL);
INSERT INTO "slat_location" VALUES(120,'Te Anau',0.36,NULL,NULL);
INSERT INTO "slat_location" VALUES(121,'Gore',0.18,NULL,NULL);
INSERT INTO "slat_location" VALUES(122,'Winton',0.2,NULL,NULL);
INSERT INTO "slat_location" VALUES(123,'Balclutha',0.13,NULL,NULL);
INSERT INTO "slat_location" VALUES(124,'Mataura',0.17,NULL,NULL);
INSERT INTO "slat_location" VALUES(125,'Bluff',0.15,NULL,NULL);
INSERT INTO "slat_location" VALUES(126,'Invercargill',0.17,NULL,NULL);
INSERT INTO "slat_location" VALUES(127,'Oban',0.14,NULL,NULL);
COMMIT;
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE "slat_edp_flavours" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name_text" varchar(25) NOT NULL);
INSERT INTO "slat_edp_flavours" VALUES(16384,'User-defined');
INSERT INTO "slat_edp_flavours" VALUES(16385,'Power Curve');
COMMIT;
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE "slat_im_types" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name_text" varchar(25) NOT NULL);
INSERT INTO "slat_im_types" VALUES(4096,'Non-Linear Hyperbolic');
INSERT INTO "slat_im_types" VALUES(4097,'Interpolated');
INSERT INTO "slat_im_types" VALUES(4098,'NZ Standard');
COMMIT;
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE "slat_input_file_formats" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "format_text" varchar(20) NOT NULL);
INSERT INTO "slat_input_file_formats" VALUES(8192,'CSV');
INSERT INTO "slat_input_file_formats" VALUES(8193,'Old SLAT');
COMMIT;
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE "slat_interpolation_method" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "method_text" varchar(20) NOT NULL);
INSERT INTO "slat_interpolation_method" VALUES(12288,'Linear');
INSERT INTO "slat_interpolation_method" VALUES(12289,'Log-Log');
COMMIT;
